Add course progression Backend side
Ollamy/Ollamy pull request #181
Opened 2024-06-11 03:32 UTC by Toumi-Elyes

## Summary

Please write a summary of your changes. Provide any information that could be
useful to the reviewer.

## Checklist

**Bureaucracy**

- [x] I set a descriptive title
- [x] I set a proper description, providing enough information to the reviewer
- [x] I considered squashing this PR, if needed
- [x] I set the proper assignee
- [x] I set the proper reviewers

**Quality Assurance**

- [ ] I tested the behavior of this PR locally and made sure it complies with
  the ticket description

2024-06-12 02:50 UTC, jeanbaptistedebize requested changes

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/middleware/middleware.guard.ts
> +const detectDevice = (userAgent: string) => {
We should be detecting whether the user is connected to the maker or the mobile app, not checking the device.

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/user/user.service.ts
> +                ctx.__device.isPhone ||
replace by isMake // isMobileApp

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/user/user.service.ts
> +                  ? status || Status.NOT_STARTED
small mistake here, replace || by ??

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/tests/data/user.data.ts
> +    isPhone: false,
fix with new values

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/user/user.service.ts
>              const {
Only do the database query if it's the mobile app

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/section/section.service.ts
> +      const userToSection = await prisma.usertoSection.findUnique({
We should make this database query only if it's the mobile app.

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/prisma/schema.prisma
> +  UsertoCourse  UsertoCourse[]
we should remove UsertoCourse from the section model.

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/section/section.service.ts
> +          section_id: sectionId,
we should include UsertoLesson in this query depending on client connected

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/section/section.service.ts
> +            numberOfLectures: lecturesCount || 0,
mistake here, replace || by ??

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/section/section.service.ts
> +      if (!userToSection) {
you don't need to make a query an manuly check, you can just create the usersecton and see if the unique contraint is trigger in the table

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/section/section.controller.ts
> +  }
This should not be the job of the frontend to call a route to join a lesson, this will add to much complexity. We should probably handle it diffrently

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/section/section.service.ts
> +    ) {
We could replace all this complex code by a simple sql query like this
```
select count(*)
from "Lesson" as L
where section_id = '<section_id>'
and not exists(
    select 1
    from  "UsertoLesson" utl
    where utl.lesson_id = L.id
        and utl.status != 'COMPLETED'
);
```

Let see how to do that in Prisma.

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/section/section.service.ts
> +    ) {
```
prisma.lesson.count({
      where: {
        UsertoLesson: {
          none: {
            status: {
              not: 'COMPLETED'
            }
          }
        }
      }
    })
```

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/lesson/lesson.service.ts
>        });
Put the usertoLesson here

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/course/course.service.ts
> +      courseSectionsIds.length === courseUserToSectionStatuses.length
we can simplify this part the way we did in the other file with one query. see bellow

2024-06-12 02:50 UTC, jeanbaptistedebize commented on packages/service-backend/src/course/course.service.ts
>          where: {
move the usertoSection query here

2024-06-16 01:11 UTC, Toumi-Elyes commented on packages/service-backend/prisma/schema.prisma
> +  UsertoCourse  UsertoCourse[]
It is automatically created since we have a relation between section and userToCourse with `last_section_id` field

2024-06-16 01:23 UTC, Toumi-Elyes commented on packages/service-backend/src/section/section.controller.ts
> +  }
We might need to talk about this then. I understand the point but just to understand the implementation method

2024-06-22 03:10 UTC, jeanbaptistedebize commented on packages/service-backend/prisma/schema.prisma
> +  UsertoCourse  UsertoCourse[]
I removed last_section_id and last_lesson_id as we no longer use them

2024-06-22 05:31 UTC, jeanbaptistedebize approved these changes

2024-06-22 05:32 UTC, merged