Backend user statistics
Ollamy/Ollamy pull request #207
Opened 2024-06-25 06:13 UTC by Toumi-Elyes

## Summary

This pr aim to add a statistic system for user and course (and all its components)

## Checklist

**Bureaucracy**

- [x] I set a descriptive title
- [x] I set a proper description, providing enough information to the reviewer
- [x] I considered squashing this PR, if needed
- [x] I set the proper assignee
- [x] I set the proper reviewers

**Quality Assurance**

- [ ] I tested the behavior of this PR locally and made sure it complies with
  the ticket description

2024-06-29 13:26 UTC, twillsonepitech commented on packages/service-backend/prisma/schema.prisma
for the field name we keep `UserSession` or `userSession`

2024-06-29 13:31 UTC, twillsonepitech approved these changes

2024-07-03 16:00 UTC, ThisisYoYoDev requested changes
Some file are formatted with space tabulation of 4 instead of 2.

2024-07-03 16:00 UTC, ThisisYoYoDev commented on packages/service-backend/setup/database_schema_create.sql
Be sure that the order id are correctly set and not just put to default value ("a0")

2024-07-03 16:00 UTC, ThisisYoYoDev commented on packages/service-backend/src/course/course.service.ts
> +  async getEnrollmentsForCourse(courseId: string, ownerId: string): Promise<EnrollmentResponseTotal> {
`getEnrollmentsForCourse` and `getEnrollmentsForOwner` are literally the same function. be sure to only made one function that choose to add or no the courseId

2024-07-03 16:00 UTC, ThisisYoYoDev commented on packages/service-backend/src/session/session.dto.ts
> +  nextQuestionId?: string;
add `| null` for typing or remove the nullable if not nullable

2024-07-03 16:00 UTC, ThisisYoYoDev commented on packages/service-backend/src/statistic/statistic.service.ts
> +  static async getGradeByTypeOfCourse(
use same row query as other function. For optimization you can also use one function to do the same things (this is possible because we use rawQuery)

2024-07-04 00:18 UTC, ThisisYoYoDev reviewed
Good for the currect change, don't forget to do the other changes

2024-07-04 04:59 UTC, ThisisYoYoDev approved these changes

2024-07-04 05:02 UTC, merged