Setup database model oll 22
Ollamy/Ollamy pull request #8
Opened 2022-12-08 18:57 UTC by Toumi-Elyes

## Summary

setup the database and the prisma orm and nest backend

## Checklist

**Bureaucracy**

- [x] I set a descriptive title
- [x] I set a proper description, providing enough information to the reviewer
- [x] I considered squashing this PR, if needed
- [x] I set the proper assignee
- [x] I set the proper reviewers

**Quality Assurance**

- [x] I tested the behavior of this PR locally and made sure it complies with
  the ticket description

2022-12-08 19:09 UTC, ThisisYoYoDev requested changes

2022-12-08 19:09 UTC, ThisisYoYoDev commented on backend/src/client.ts
> +  console.log(`Database connected`);
Why use injected string here ?

2022-12-08 19:09 UTC, ThisisYoYoDev commented on backend/src/user/user.service.ts
> +  async postUser(userData: UserModel): Promise<string | null> {
When you return null ?

2022-12-08 19:09 UTC, ThisisYoYoDev commented on docker-compose.yml
> +  # backend:
Remove comment

2022-12-09 11:24 UTC, jeanbaptistedebize commented on backend/prisma/schema.prisma
> +  crew_id String
inverse relation

2022-12-09 11:25 UTC, jeanbaptistedebize commented on backend/prisma/migrations/20221206172321_init/migration.sql
> +ALTER TABLE "Lessons" ADD CONSTRAINT "Lessons_chapter_id_fkey" FOREIGN KEY ("chapter_id") REFERENCES "Chapter"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
Fix `on delete restrict` to `on delete cascade`.

2022-12-09 11:26 UTC, jeanbaptistedebize commented on backend/prisma/schema.prisma
> +  id             String   @id @unique @default(uuid())
remove unique

2022-12-09 13:55 UTC, jeanbaptistedebize commented on backend/src/main.ts
> +import * as cookieParser from 'cookie-parser';
only import require module plz

2022-12-09 13:57 UTC, jeanbaptistedebize commented on backend/src/setup.ts
> +import * as dotenv from 'dotenv';
same

2022-12-09 14:01 UTC, jeanbaptistedebize commented on backend/src/user/user.service.ts
> +  validateEmail(email: string) {
should be private ?

2022-12-09 14:05 UTC, jeanbaptistedebize commented on backend/src/user/user.service.ts
> +
move it in try catch here

2022-12-09 15:20 UTC, jeanbaptistedebize approved these changes

2022-12-09 15:21 UTC, merged