Oll 264 creation of a new lecture table with his crud operations
Ollamy/Ollamy pull request #88
Opened 2024-01-15 15:11 UTC by twillsonepitech

## Summary

Please write a summary of your changes. Provide any information that could be
useful to the reviewer.

## Checklist

**Bureaucracy**

- [ ] I set a descriptive title
- [ ] I set a proper description, providing enough information to the reviewer
- [ ] I considered squashing this PR, if needed
- [ ] I set the proper assignee
- [ ] I set the proper reviewers

**Quality Assurance**

- [ ] I tested the behavior of this PR locally and made sure it complies with
  the ticket description

2024-01-20 00:17 UTC, ThisisYoYoDev requested changes

2024-01-20 00:17 UTC, ThisisYoYoDev commented on packages/service-backend/src/lecture/lecture.dto.ts
> +  data: string;
`data` should be Optional

2024-01-20 00:17 UTC, ThisisYoYoDev commented on packages/service-backend/src/lecture/lecture.service.ts
> +            const lectureDb = await prisma.lecture.findFirst({
`findFirst` should be `findOne`

2024-01-22 06:38 UTC, twillsonepitech commented on packages/service-backend/src/lecture/lecture.dto.ts
> +  data: string;
done

2024-01-22 06:38 UTC, twillsonepitech commented on packages/service-backend/src/lecture/lecture.service.ts
> +            const lectureDb = await prisma.lecture.findFirst({
findOne doesn't exist ?

2024-01-22 20:38 UTC, ThisisYoYoDev commented on packages/service-backend/src/lecture/lecture.service.ts
> +            const lectureDb = await prisma.lecture.findFirst({
`findUnique` sorry

2024-01-26 18:56 UTC, twillsonepitech commented on packages/service-backend/src/lecture/lecture.service.ts
> +            const lectureDb = await prisma.lecture.findFirst({
done

2024-01-26 20:13 UTC, ThisisYoYoDev approved these changes

2024-01-26 20:44 UTC, merged